@default:
    just --list
build-run:
    mvn package
    mvn exec:java -Dexec.mainClass="com.${{PROJECT_NAME:safe_name}}.app.App"
run:
    mvn exec:java -Dexec.mainClass="com.${{PROJECT_NAME:safe_name}}.app.App"
build:
    mvn package
clean:
    mvn clean
